hadoop_home: /home/hadoop/hadoop-3.2.1
hadoop_base: /home/hadoop
mirror_ftp: "http://ftp.unicamp.br/pub/apache/hadoop/common/stable/hadoop-3.2.1.tar.gz"
java_home: /usr/lib/jvm/java-1.8.0-openjdk-amd64
user_name: hadoop
user_password: hadoop